apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
  namespace: bootcamp
spec:
  replicas: 2
  progressDeadlineSeconds: 600
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: greeting
        env: testing
        project: bootcamp
    spec:
      containers:
      - name: greeting
        image: wimsie/bootcamp-greeting:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "500Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        env:
        - name: TZ
          value: "Europe/Berlin"
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 100
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
          failureThreshold: 2
      restartPolicy: Always
