apiVersion: v1
kind: Service
metadata:
  name: greeting
  labels:
    app: greeting
    env: testing
  namespace: bootcamp
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: greeting
    env: testing
